[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_pattern = "aks-.*-renku-prod"
style = "bold red"
symbol = "ğŸ’” "

[[kubernetes.contexts]]
context_pattern = "aks-.*-renku-dev"
style = "blue"
symbol = "ğŸ› ï¸ "
